# Generated by Django 4.0 on 2022-03-27 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0002_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
